name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: azaharizaman
          template: classic
          base: header, activity, community, repositories, metadata
          config_animations: yes
          config_timezone: Asia\Kuching
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year         
          plugin_languages: yes
          plugin_lines: yes
          plugin_repositories: yes
          plugin_repositories_featured: azaharizsaman/october
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_from: 250
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
